services:
  grafana:
    user: root
    container_name: 'dbeast-dbeastmonitor-app'

    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.0.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../grafana:/var/lib/grafana
      - .:/root/dbeast-dbeastmonitor-app
      - ../provisioning:/etc/grafana/provisioning

    environment:
      GF_SERVER_HTTP_ADDR: 0.0.0.0
      GF_LOG_LEVEL: info
      GF_DATAPROXY_LOGGING: 1
      GF_INSTALL_PLUGINS: "dbeast-dbeastmonitor-app"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"

    entrypoint: ["/entrypoint.sh"]

  logstash-init:
    extends:
      file: docker/docker-compose-elastic-stack-grafana.yaml
      service: logstash-init

  logstash:
    extends:
      file: docker/docker-compose-elastic-stack-grafana.yaml
      service: es-base
    container_name: logstash-mon

  es-prod-01:
    extends:
      file: docker/docker-compose-elastic-stack-grafana.yaml
      service: es-base
    container_name: es-prod-01
    environment:
      - cluster.name=es-prod
      - node.name=es-prod-01
      - discovery.seed_hosts=es-prod-01,es-prod-02,es-prod-03
      - cluster.initial_master_nodes=es-prod-01,es-prod-02,es-prod-03
    ports:
      - "9200:9200"
    volumes:
      - es-prod-01_data:/usr/share/elasticsearch/data

  es-prod-02:
    extends:
      file: docker/docker-compose-elastic-stack-grafana.yaml
      service: es-base
    container_name: es-prod-02
    environment:
      - cluster.name=es-prod
      - node.name=es-prod-02
      - discovery.seed_hosts=es-prod-01,es-prod-02,es-prod-03
      - cluster.initial_master_nodes=es-prod-01,es-prod-02,es-prod-03
    volumes:
      - es-prod-02_data:/usr/share/elasticsearch/data

  es-prod-03:
    extends:
      file: docker/docker-compose-elastic-stack-grafana.yaml
      service: es-base
    container_name: es-prod-03
    environment:
      - cluster.name=es-prod
      - node.name=es03
      - discovery.seed_hosts=es-prod-01,es-prod-02,es-prod-03
      - cluster.initial_master_nodes=es-prod-01,es-prod-02,es-prod-03
    volumes:
      - es-prod-03_data:/usr/share/elasticsearch/data

  kibana-prod:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: kibana-prod
    depends_on:
      - es-prod-01
    environment:
      - SERVER_PUBLICBASEURL=http://localhost:5601
      - ELASTICSEARCH_HOSTS=http://es-prod-01:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    networks:
      - elk


volumes:
  es-prod-01_data:
  es-prod-02_data:
  es-prod-03_data:

networks:
  elk:
    driver: bridge
