services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.18.1
    container_name: metricbeat
    user: root
    volumes:
      - ./docker/metricbeat.template.yml:/usr/share/metricbeat/metricbeat.template.yml
      - ./docker/metricbeat-entrypoint.sh:/usr/local/bin/metricbeat-entrypoint.sh
    entrypoint: [ "/usr/local/bin/metricbeat-entrypoint.sh" ]
