{
 "title": "Elasticsearch index overview",
 "tags": [
  "DBeastMonitor",
  "OverviewDashboard"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster Name",
    "query": {}
   },
   { "name": "es_index_stats", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "es_index_stats_status", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "index_name", "label": "index_name" }
  ]
 },
 "panels": [
  { "title": "Cluster rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingest rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.index.primaries.indexing.index_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats and elasticsearch.index.primaries.indexing.index_rate>1 ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.index.total.search.query_rate",
       "id": "1",
       "settings": { "script": "_value >0 ? _value : 0" },
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ingest rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "elasticsearch.index.primaries.indexing.index_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "elasticsearch.index.total.search.query_rate",
       "hide": false,
       "id": "1",
       "settings": { "script": "_value >0 ? _value : 0" },
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Index patterns overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index patterns",
     "type": "table",
     "gridPos": { "h": 21, "w": 19, "x": 2, "y": 17 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.index.index_pattern",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "0" },
         "type": "terms"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.index.total.store.size_in_bytes",
         "id": "1",
         "type": "sum"
        },
        {
         "field": "elasticsearch.index.primaries.store.size_in_bytes",
         "id": "3",
         "type": "sum"
        },
        {
         "field": "elasticsearch.index.primaries.indexing.index_rate",
         "id": "4",
         "type": "sum"
        },
        {
         "field": "elasticsearch.index.total.search.query_rate",
         "id": "5",
         "type": "sum"
        },
        {
         "id": "6",
         "type": "min",
         "field": "elasticsearch.index.shards.primaries"
        },
        {
         "id": "7",
         "type": "max",
         "field": "elasticsearch.index.shards.primaries"
        },
        { "type": "count", "id": "8" }
       ],
       "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats AND elasticsearch.index.name: *$index_name*",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Indices overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Index stats",
   "type": "table",
   "gridPos": { "h": 21, "w": 19, "x": 2, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.health",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "elasticsearch.index.name",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "9", "size": "0" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.index.total.store.size_in_bytes",
       "id": "1",
       "type": "sum"
      },
      {
       "field": "elasticsearch.index.primaries.store.size_in_bytes",
       "id": "3",
       "type": "sum"
      },
      {
       "field": "elasticsearch.index.primaries.indexing.index_rate",
       "id": "4",
       "type": "sum"
      },
      {
       "field": "elasticsearch.index.total.search.query_rate",
       "id": "5",
       "type": "sum"
      },
      {
       "field": "elasticsearch.index.shards.primaries",
       "id": "8",
       "type": "max"
      },
      {
       "field": "elasticsearch.index.total.docs.count",
       "id": "9",
       "type": "max"
      },
      {
       "field": "elasticsearch.index.shards.total",
       "id": "12",
       "type": "max"
      },
      {
       "id": "13",
       "type": "bucket_script",
       "pipelineVariables": [
        { "name": "pri_store", "pipelineAgg": "3" },
        { "name": "pri_shards", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.pri_store / params.pri_shards"
       }
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats AND elasticsearch.index.name: *$index_name*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}