{
 "title": "Elasticsearch index patterns overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster UID",
    "query": {}
   },
   { "name": "es_index_stats", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "es_index_stats_status", "label": "Elastic datasource", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Top biggest index patterns",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.index.total.store.size_in_bytes",
       "id": "1",
       "type": "sum"
      },
      {
       "field": "elasticsearch.index.primaries.store.size_in_bytes",
       "id": "3",
       "type": "sum"
      },
      {
       "field": "elasticsearch.index.primaries.indexing.index_rate",
       "id": "4",
       "type": "sum"
      },
      {
       "field": "elasticsearch.index.total.search.query_rate",
       "id": "5",
       "type": "sum"
      },
      { "id": "6", "type": "count" }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ingest rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "elasticsearch.index.primaries.indexing.index_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats AND elasticsearch.index.primaries.indexing.index_rate:>1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "elasticsearch.index.total.search.query_rate",
       "hide": false,
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats AND elasticsearch.index.total.search.query_rate:>1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ingest rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.index.primaries.indexing.index_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats AND elasticsearch.index.primaries.indexing.index_rate:>1 ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.index.total.search.query_rate",
       "id": "1",
       "settings": { "script": "_value >0 ? _value : 0" },
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: index_stats AND elasticsearch.index.total.search.query_rate:>1",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}