{
 "title": "Logstash node overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster UID",
    "query": {}
   },
   { "name": "logstash_mon_metrics", "label": "logstash_mon_metrics", "query": "elasticsearch" },
   { "name": "logstash_mon_metrics_status", "label": "logstash_mon_metrics_status", "query": "elasticsearch" },
   { "name": "logstash_mon_logs", "label": "logstash_mon_logs", "query": "elasticsearch" },
   { "name": "es_direct_mon", "label": "Elastic datasource", "query": "marcusolsson-json-datasource" },
   {
    "name": "ls_host",
    "label": "Logstash host",
    "query": {}
   },
   { "name": "logstash_mon_logs_ports", "label": "logstash_mon_logs_ports", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Node information",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "Logstash host: {{host}}  <br />\nLogstash name: {{name}} <br />\nStatus: {{status}} <br />"
   },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.logstash.host",
       "name": "host"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.logstash.name",
       "language": "jsonpath",
       "name": "name"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.logstash.status",
       "language": "jsonpath",
       "name": "status"
      }
     ],
     "method": "GET",
     "params": [
      [
       "q",
       "metricset.name:node_stats AND host.hostname:$ls_host"
      ]
     ],
     "urlPath": "/mon-logstash-metrics-status/_search"
    }
   ]
  },
  {
   "title": "Data flow rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.events.in_rate",
       "id": "1",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.events.out_rate",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "metricset.name: node_stats AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipelines ingest rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.pipeline.events.out_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "metricset.name: pipelines AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.process.cpu.percent",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: node_stats AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JVM heap usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.jvm.mem.heap_used_percent",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: node_stats AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline overview",
   "type": "table",
   "gridPos": { "h": 20, "w": 13, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.pipeline.events.in",
       "id": "1",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.in_rate",
       "id": "4",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.out",
       "id": "5",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.out_rate",
       "id": "6",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.plugins.filters.failures_rate",
       "id": "7",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.plugins.filters.failures",
       "id": "8",
       "type": "max"
      }
     ],
     "query": "metricset.name: pipelines AND elasticsearch.cluster.id: $cluster_uid AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "logstash.log.pipeline_listener_port",
       "id": "1",
       "type": "max",
       "settings": { "missing": "0" }
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Exception list",
   "type": "table",
   "gridPos": { "h": 20, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.log.pipeline_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "logstash.exception.type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event.dataset: logstash_logs AND logstash.log.type: Exception AND host.hostname: $ls_host AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}