apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-logstash
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-logstash
    spec:
      initContainers:
        - name: logstash-init
          image: {{ .Values.logstash.image }}
          command:
            - sh
            - -c
            - |
              if [ -z "$(ls -A /tmp/logstash)" ]; then
                echo "Persistent volume is empty. Copying data from image..."
                cp -R /usr/share/logstash/config/* /tmp/logstash/
                mkdir -p /tmp/logstash/conf.d
              else
                echo "Persistent volume is not empty. Skipping data copy."
              fi
          volumeMounts:
            - name: logstash-config-pvc
              mountPath: /tmp/logstash

      containers:
      - name: logstash
        securityContext:
          runAsUser: 0
        image: {{ .Values.logstash.image }}
        ports:
        - containerPort: 5044
        env:
        {{- range .Values.logstash.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        volumeMounts:
          - name: logstash-config-pvc
            mountPath: /usr/share/logstash/config
          - name: logstash-yml
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: logstash.yml
          - name: logstash-lib
            mountPath: /var/lib/logstash
          - name: logstash-logs
            mountPath: /var/log/logstash
        {{- range .Values.logstash.volumes }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
        {{- end }}
      volumes:
        - name: logstash-config-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logstash-config-pvc
        - name: logstash-lib
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logstash-lib-pvc
        - name: logstash-logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logstash-logs-pvc
        - name: logstash-yml
          configMap:
            name: {{ .Release.Name }}-logstash-config
            items:
              - key: logstash.yml
                path: logstash.yml
      {{- range .Values.logstash.volumes }}
        - name: {{ .name }}
          {{- if .source.configMap }}
          configMap:
            name: {{ .source.configMap.name }}
            {{- if .source.configMap.key }}
            items:
              - key: {{ .source.configMap.key }}
                path: {{ .source.configMap.path | default .source.configMap.key }}
            {{- end }}
          {{- else if .source.persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ .source.persistentVolumeClaim.claimName }}
        {{- end }}
      {{- end }}
