{
 "title": "Host overview",
 "tags": [ "DBeastMonitor" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster Name",
    "query": {}
   },
   { "name": "es_metrics", "label": "es_metrics", "query": "elasticsearch" },
   { "name": "es_direct_prod", "label": "Elastic datasource", "query": "marcusolsson-json-datasource" },
   {
    "name": "node_name",
    "label": "Node name",
    "query": "{\"find\": \"terms\", \"field\": \"elasticsearch.node.name\", \"query\": \"elasticsearch.cluster.id: $cluster_uid\" }"
   },
   {
    "name": "node_host",
    "label": "Node host",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\", \"query\": \"elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.name: $node_name AND event.dataset: elasticsearch.node.stats\"}"
   },
   { "name": "es_shards_stats", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "filebeat_logs", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "es_shards_stats_status", "label": "Elastic datasource", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Node stats",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "language": "jsonpath", "name": "Node name" },
      { "jsonPath": "$.nodes.*.transport_address", "language": "jsonpath", "name": "Transport address" },
      {
       "jsonPath": "$.nodes.*.indices.shard_stats.total_count",
       "language": "jsonpath",
       "name": "Number of shards"
      },
      { "jsonPath": "$.nodes.*.indices.docs.count", "language": "jsonpath", "name": "Docs count" },
      { "jsonPath": "$.nodes.*.indices.docs.deleted", "language": "jsonpath", "name": "Docs deleted" },
      {
       "jsonPath": "$.nodes.*.fs.total.total_in_bytes",
       "language": "jsonpath",
       "name": "Total space"
      },
      {
       "jsonPath": "$.nodes.*.fs.total.available_in_bytes",
       "language": "jsonpath",
       "name": "Free space"
      },
      { "jsonPath": "$.nodes.*.jvm.uptime_in_millis", "language": "jsonpath", "name": "Uptime" },
      {
       "jsonPath": "$.nodes.*.jvm.mem.heap_max_in_bytes",
       "language": "jsonpath",
       "name": "JVM Heap"
      },
      {
       "name": "Node roles",
       "jsonPath": "$.nodes.*.$join($map(roles, $string), \", \")",
       "language": "jsonata"
      }
     ],
     "method": "GET",
     "urlPath": "/_nodes/$node_name/stats?filter_path=nodes.*.roles,nodes.*.jvm.uptime_in_millis,nodes.*.indices.docs.count,nodes.*.indices.docs.deleted,nodes.*.indices.shard_stats.total_count,nodes.*.name,nodes.*.transport_address,nodes.*.jvm.mem.heap_max_in_bytes,nodes.*.fs.total.total_in_bytes,nodes.*.fs.total.available_in_bytes"
    }
   ]
  },
  { "title": "Server level Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.cpu.cores",
       "hide": false,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "host.hostname: $node_host AND event.dataset: system.cpu",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.memory.total",
       "hide": false,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "host.hostname: $node_host AND event.dataset: system.memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SWAP used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.memory.swap.total",
       "hide": false,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "host.hostname: $node_host AND event.dataset: system.memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mount points size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.filesystem.mount_point",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "field": "system.filesystem.total", "id": "1", "type": "max" }
     ],
     "query": "host.hostname: $node_host AND -system.filesystem.mount_point:\\/run* AND -system.filesystem.mount_point:\\/sys* AND -system.filesystem.mount_point:\\/dev* AND -system.filesystem.mount_point:\\/proc* AND -system.filesystem.mount_point:\\/var* AND -system.filesystem.mount_point:\\/boot",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mount points free in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.filesystem.mount_point",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "field": "system.filesystem.available", "id": "1", "type": "max" }
     ],
     "query": "host.hostname: $node_host AND -system.filesystem.mount_point:\\/run* AND -system.filesystem.mount_point:\\/sys* AND -system.filesystem.mount_point:\\/dev* AND -system.filesystem.mount_point:\\/proc* AND -system.filesystem.mount_point:\\/var* AND -system.filesystem.mount_point:\\/boot",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mount points used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.filesystem.mount_point",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "field": "system.filesystem.used.pct", "id": "1", "type": "max" }
     ],
     "query": "host.hostname: $node_host AND -system.filesystem.mount_point:\\/run* AND -system.filesystem.mount_point:\\/sys* AND -system.filesystem.mount_point:\\/dev* AND -system.filesystem.mount_point:\\/proc* AND -system.filesystem.mount_point:\\/var* AND -system.filesystem.mount_point:\\/boot",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.cpu.user.norm.pct",
       "hide": false,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "system.cpu.system.norm.pct",
       "hide": false,
       "id": "3",
       "type": "avg"
      },
      {
       "field": "system.cpu.nice.norm.pct",
       "hide": false,
       "id": "4",
       "type": "avg"
      },
      {
       "field": "system.cpu.softirq.norm.pct",
       "hide": false,
       "id": "5",
       "type": "avg"
      },
      {
       "field": "system.cpu.irq.norm.pct",
       "hide": false,
       "id": "6",
       "type": "avg"
      },
      {
       "field": "system.cpu.iowait.norm.pct",
       "hide": false,
       "id": "7",
       "type": "avg"
      }
     ],
     "query": "event.dataset: system.cpu AND host.hostname: $node_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.memory.actual.used.bytes",
       "hide": false,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "system.memory.used.bytes",
       "hide": true,
       "id": "4",
       "type": "avg"
      },
      {
       "id": "5",
       "pipelineVariables": [
        { "name": "actual", "pipelineAgg": "1" },
        { "name": "used", "pipelineAgg": "4" }
       ],
       "settings": {
        "script": "params.actual != null && params.used != null ? params.used - params.actual : null"
       },
       "type": "bucket_script"
      },
      { "field": "system.memory.free", "id": "6", "type": "avg" }
     ],
     "query": "host.hostname: $node_host AND event.dataset: system.memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.network.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "type": "max",
       "settings": { "script": "_value/60" }
      },
      {
       "field": "1",
       "hide": false,
       "id": "3",
       "pipelineAgg": "1",
       "settings": { "unit": "1m" },
       "type": "derivative"
      },
      {
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "5",
       "type": "max",
       "settings": { "script": "_value/60" }
      },
      {
       "field": "5",
       "hide": true,
       "id": "6",
       "pipelineAgg": "5",
       "settings": { "unit": "1m" },
       "type": "derivative"
      },
      {
       "id": "7",
       "pipelineVariables": [
        { "name": "out", "pipelineAgg": "6" }
       ],
       "settings": { "script": "params.out * -1" },
       "type": "bucket_script"
      }
     ],
     "query": "event.dataset: system.network AND host.hostname: $node_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Write IOPS",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.diskio.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": {
        "interval": "1m",
        "min_doc_count": "0",
        "offset": "1m",
        "timeZone": "utc",
        "trimEdges": "0"
       },
       "type": "date_histogram"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.diskio.write.count",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "1",
       "hide": true,
       "id": "4",
       "pipelineAgg": "1",
       "type": "derivative"
      },
      {
       "id": "5",
       "pipelineVariables": [
        { "name": "io", "pipelineAgg": "4" }
       ],
       "settings": { "script": "params.io / 60" },
       "type": "bucket_script"
      }
     ],
     "query": "host.hostname: $node_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processes By Memory",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "process.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1m", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "field": "system.process.memory.rss.pct", "id": "1", "type": "max" }
     ],
     "query": "process.name:* AND host.name: $node_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network dropped packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.network.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.network.in.dropped",
       "hide": true,
       "id": "1",
       "type": "max"
      },
      {
       "field": "1",
       "hide": false,
       "id": "3",
       "pipelineAgg": "1",
       "settings": { "unit": "1m" },
       "type": "derivative"
      },
      {
       "field": "system.network.out.dropped",
       "hide": true,
       "id": "5",
       "type": "max"
      },
      {
       "field": "5",
       "hide": true,
       "id": "6",
       "pipelineAgg": "5",
       "settings": { "unit": "1m" },
       "type": "derivative"
      },
      {
       "id": "7",
       "pipelineVariables": [
        { "name": "out", "pipelineAgg": "6" }
       ],
       "settings": { "script": "params.out * -1" },
       "type": "bucket_script"
      }
     ],
     "query": "event.dataset: system.network AND host.hostname: $node_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Read  IOPS",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.diskio.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": {
        "interval": "1m",
        "min_doc_count": "0",
        "offset": "1m",
        "timeZone": "utc",
        "trimEdges": "0"
       },
       "type": "date_histogram"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.diskio.read.count",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "1",
       "hide": true,
       "id": "4",
       "pipelineAgg": "1",
       "type": "derivative"
      },
      {
       "id": "5",
       "pipelineVariables": [
        { "name": "io", "pipelineAgg": "4" }
       ],
       "settings": { "script": "params.io / 60" },
       "type": "bucket_script"
      }
     ],
     "query": "host.hostname: $node_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processes By CPU",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "process.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1m", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "field": "system.process.cpu.total.pct", "id": "1", "type": "max" }
     ],
     "query": "process.name:* AND host.name: $node_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network error packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.network.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "system.network.in.errors",
       "hide": true,
       "id": "1",
       "type": "max"
      },
      {
       "field": "1",
       "hide": false,
       "id": "3",
       "pipelineAgg": "1",
       "settings": { "unit": "1m" },
       "type": "derivative"
      },
      {
       "field": "system.network.out.errors",
       "hide": true,
       "id": "5",
       "type": "max"
      },
      {
       "field": "5",
       "hide": true,
       "id": "6",
       "pipelineAgg": "5",
       "settings": { "unit": "1m" },
       "type": "derivative"
      },
      {
       "id": "7",
       "pipelineVariables": [
        { "name": "out", "pipelineAgg": "6" }
       ],
       "settings": { "script": "params.out * -1" },
       "type": "bucket_script"
      }
     ],
     "query": "event.dataset: system.network AND host.hostname: $node_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node level Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingest rate (EPS)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.indices.indexing.index_total.count",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "3",
         "pipelineAgg": "1",
         "type": "derivative"
        },
        {
         "hide": false,
         "id": "4",
         "pipelineVariables": [
          { "name": "der", "pipelineAgg": "3" }
         ],
         "settings": {
          "script": "params.der > 0? params.der/60 : 0"
         },
         "type": "bucket_script"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: node_stats AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Search rate (QPS)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.indices.search.query_total.count",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "3",
         "pipelineAgg": "1",
         "type": "derivative"
        },
        {
         "hide": false,
         "id": "4",
         "pipelineVariables": [
          { "name": "der", "pipelineAgg": "3" }
         ],
         "settings": {
          "script": "params.der > 0? params.der/60 : 0"
         },
         "type": "bucket_script"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: node_stats AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "JVM heap usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
     "targets": [
      {
       "alias": "Heap usage",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.jvm.mem.heap.used.pct",
         "hide": false,
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND event.dataset: elasticsearch.node.stats AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Ingest latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.indices.indexing.index_total.count",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "3",
         "pipelineAgg": "1",
         "type": "derivative"
        },
        {
         "field": "elasticsearch.node.stats.indices.indexing.index_time.ms",
         "hide": true,
         "id": "5",
         "type": "max"
        },
        {
         "field": "5",
         "hide": true,
         "id": "6",
         "pipelineAgg": "5",
         "type": "derivative"
        },
        {
         "id": "7",
         "pipelineVariables": [
          { "name": "count", "pipelineAgg": "3" },
          { "name": "duration", "pipelineAgg": "6" }
         ],
         "settings": {
          "script": "params.count > 0 ? params.duration / params.count : 0"
         },
         "type": "bucket_script"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: node_stats AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Search latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.indices.search.query_total.count",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "3",
         "pipelineAgg": "1",
         "type": "derivative"
        },
        {
         "field": "elasticsearch.node.stats.indices.search.query_time.ms",
         "hide": true,
         "id": "5",
         "type": "max"
        },
        {
         "field": "5",
         "hide": true,
         "id": "6",
         "pipelineAgg": "5",
         "type": "derivative"
        },
        {
         "id": "7",
         "pipelineVariables": [
          { "name": "count", "pipelineAgg": "3" },
          { "name": "duration", "pipelineAgg": "6" }
         ],
         "settings": {
          "script": "params.count > 0 ? params.duration / params.count : 0"
         },
         "type": "bucket_script"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: node_stats AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "GC count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.jvm.gc.collectors.young.collection.count",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "3",
         "pipelineAgg": "1",
         "type": "derivative"
        },
        {
         "hide": false,
         "id": "4",
         "pipelineVariables": [
          { "name": "young", "pipelineAgg": "3" }
         ],
         "settings": {
          "script": "((params.young / 60 / 60) > 0 ) ? (params.young / 60 ) : 0"
         },
         "type": "bucket_script"
        },
        {
         "field": "elasticsearch.node.stats.jvm.gc.collectors.old.collection.count",
         "hide": true,
         "id": "5",
         "type": "max"
        },
        {
         "field": "5",
         "hide": true,
         "id": "6",
         "pipelineAgg": "5",
         "type": "derivative"
        },
        {
         "hide": false,
         "id": "7",
         "pipelineVariables": [
          { "name": "duration", "pipelineAgg": "6" }
         ],
         "settings": {
          "script": "((params.duration / 60) > 0 ) ? (params.duration / 60) : 0"
         },
         "type": "bucket_script"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.cluster.id: $cluster_uid AND event.dataset: elasticsearch.node.stats AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "CPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": "CPU utilization",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.process.cpu.pct",
         "hide": false,
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND event.dataset: elasticsearch.node.stats AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Segment count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.indices.segments.count",
         "hide": false,
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND event.dataset: elasticsearch.node.stats AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Avg GC duration (ms)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.jvm.gc.collectors.old.collection.count",
         "hide": true,
         "id": "4",
         "type": "max"
        },
        {
         "field": "elasticsearch.node.stats.jvm.gc.collectors.young.collection.count",
         "hide": true,
         "id": "5",
         "type": "max"
        },
        {
         "field": "elasticsearch.node.stats.jvm.gc.collectors.old.collection.ms",
         "hide": true,
         "id": "6",
         "type": "max"
        },
        {
         "field": "elasticsearch.node.stats.jvm.gc.collectors.young.collection.ms",
         "hide": true,
         "id": "7",
         "type": "max"
        },
        {
         "field": "4",
         "hide": true,
         "id": "8",
         "pipelineAgg": "4",
         "type": "derivative"
        },
        {
         "field": "5",
         "hide": true,
         "id": "9",
         "pipelineAgg": "5",
         "type": "derivative"
        },
        {
         "field": "6",
         "hide": true,
         "id": "10",
         "pipelineAgg": "6",
         "type": "derivative"
        },
        {
         "field": "7",
         "hide": true,
         "id": "11",
         "pipelineAgg": "7",
         "type": "derivative"
        },
        {
         "id": "12",
         "pipelineVariables": [
          { "name": "young_count", "pipelineAgg": "9" },
          { "name": "young_ms", "pipelineAgg": "11" }
         ],
         "settings": {
          "script": "params.young_count > 0 ? params.young_ms/ params.young_count: 0"
         },
         "type": "bucket_script"
        },
        {
         "id": "13",
         "pipelineVariables": [
          { "name": "old_count", "pipelineAgg": "9" },
          { "name": "old_ms", "pipelineAgg": "10" }
         ],
         "settings": {
          "script": "params.old_ms> 0 ? params.old_count / params.old_ms : 0"
         },
         "type": "bucket_script"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND event.dataset: elasticsearch.node.stats AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Data relocation",
     "type": "table",
     "gridPos": { "h": 6, "w": 17, "x": 3, "y": 24 },
     "targets": [
      {
       "fields": [
        {
         "jsonPath": "$[(source_node = $node_name[0] or target_node = $node_name[0] )].index",
         "language": "jsonata",
         "name": "index"
        },
        {
         "jsonPath": "$[(source_node = $node_name[0] or target_node = $node_name[0] )].shard",
         "language": "jsonata",
         "name": "shard"
        },
        {
         "jsonPath": "$[(source_node = $node_name[0] or target_node = $node_name[0] )].time",
         "language": "jsonata",
         "name": "time"
        },
        {
         "jsonPath": "$[(source_node = $node_name[0] or target_node = $node_name[0] )].source_node",
         "language": "jsonata",
         "name": "source_node"
        },
        {
         "jsonPath": "$[(source_node = $node_name[0] or target_node = $node_name[0] )].target_node",
         "language": "jsonata",
         "name": "target_node"
        },
        {
         "jsonPath": "$[(source_node = $node_name[0] or target_node = $node_name[0] )].bytes_total",
         "language": "jsonata",
         "name": "bytes_total"
        },
        {
         "jsonPath": "$[(source_node = $node_name[0] or target_node = $node_name[0] )].bytes_percent",
         "language": "jsonata",
         "name": "bytes_percent"
        },
        {
         "jsonPath": "$[(source_node = $node_name[0] or target_node = $node_name[0] )].files_percent",
         "language": "jsonata",
         "name": "files_percent"
        },
        {
         "jsonPath": "$[(source_node = $node_name[0] or target_node = $node_name[0] )].translog_ops_percent",
         "language": "jsonata",
         "name": "translog_ops_percent"
        }
       ],
       "method": "GET",
       "params": [
        [
         "active_only",
         "true"
        ],
        [
         "format",
         "json"
        ]
       ],
       "urlPath": "/_cat/recovery"
      }
     ]
    }
   ]
  },
  {
   "title": "Shards level stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shards per index stats",
     "type": "table",
     "gridPos": { "h": 14, "w": 18, "x": 3, "y": 30 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.index.name",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        {
         "field": "elasticsearch.shard.store.size_in_bytes",
         "id": "3",
         "type": "avg"
        },
        {
         "field": "elasticsearch.shard.store.size_in_bytes",
         "id": "4",
         "type": "sum"
        },
        { "field": "elasticsearch.shard.docs.count", "id": "5", "type": "avg" },
        { "field": "elasticsearch.shard.docs.count", "id": "6", "type": "sum" }
       ],
       "query": "NOT elasticsearch.shard.state: UNASSIGNED AND elasticsearch.node.name: $node_name AND elasticsearch.cluster.id: $cluster_uid",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Shards ingest rates (EPS)",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.index.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": {
          "interval": "auto",
          "min_doc_count": "1",
          "offset": "0m",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.shard.indexing.index_rate",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "sum"
        },
        {
         "field": "@timestamp",
         "hide": true,
         "id": "5",
         "type": "cardinality"
        },
        {
         "id": "6",
         "pipelineVariables": [
          { "name": "sum", "pipelineAgg": "1" },
          { "name": "count", "pipelineAgg": "5" }
         ],
         "settings": { "script": "params.sum/params.count" },
         "type": "bucket_script"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.indexing.index_rate: [1 TO 100000] AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Search Operations Over Recent Period (Count)",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.index.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": {
          "interval": "auto",
          "min_doc_count": "1",
          "offset": "0m",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.shard.search.query_last_period",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "sum"
        },
        {
         "field": "@timestamp",
         "hide": true,
         "id": "5",
         "type": "cardinality"
        },
        {
         "id": "6",
         "pipelineVariables": [
          { "name": "sum", "pipelineAgg": "1" },
          { "name": "count", "pipelineAgg": "5" }
         ],
         "settings": { "script": "params.sum/params.count" },
         "type": "bucket_script"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.search.query_last_period: [10 TO 100000] AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Fetch Operations Over Recent Period (Count)",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.index.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": {
          "interval": "auto",
          "min_doc_count": "1",
          "offset": "0m",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.shard.search.fetch_last_period",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.search.fetch_last_period: [1 TO 100000] AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Shards ingest latency (ms)",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.index.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": {
          "interval": "auto",
          "min_doc_count": "1",
          "offset": "0m",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.shard.indexing.index_latency",
         "id": "1",
         "type": "avg"
        },
        {
         "field": "@timestamp",
         "hide": true,
         "id": "5",
         "type": "cardinality"
        },
        {
         "hide": true,
         "id": "6",
         "pipelineVariables": [
          { "name": "sum", "pipelineAgg": "1" },
          { "name": "count", "pipelineAgg": "5" }
         ],
         "settings": { "script": "params.sum/params.count" },
         "type": "bucket_script"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.indexing.index_latency: [1 TO 100000] AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Shards query latency (ms)",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.index.index_pattern",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": {
          "interval": "auto",
          "min_doc_count": "1",
          "offset": "0m",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.shard.search.query_latency",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.search.query_latency: [1 TO 100000] AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Shards fetch latency (ms)",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.index.index_pattern",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": {
          "interval": "auto",
          "min_doc_count": "1",
          "offset": "0m",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.shard.search.fetch_latency",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.search.fetch_latency: [10 TO 100000] AND elasticsearch.node.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "host.name: $node_name",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}