{
 "title": "Logstash node overview",
 "tags": [ "DBeastMonitor" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster Name",
    "query": {}
   },
   { "name": "logstash_mon_metrics", "label": "logstash_mon_metrics", "query": "elasticsearch" },
   { "name": "logstash_mon_metrics_status", "label": "logstash_mon_metrics_status", "query": "elasticsearch" },
   { "name": "logstash_mon_logs", "label": "logstash_mon_logs", "query": "elasticsearch" },
   {
    "name": "ls_host",
    "label": "Logstash host",
    "query": "{\"find\": \"terms\", \"field\": \"host.hostname\", \"query\": \"elasticsearch.cluster.id: $cluster_uid\" }"
   },
   { "name": "es_metrics", "label": "es_metrics", "query": "elasticsearch" },
   { "name": "logstash_mon_logs_ports", "label": "logstash_mon_logs_ports", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Instance information",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "Logstash host: {{host}}  <br />\nLogstash name: {{name}} <br />\nStatus: {{status}} <br />\nVersion: {{version}} <br />\nHttp Address: {{http_addresss}} <br />\nCurrent In rate: {{in_rate}} <br />\nCurrent Out rate: {{out_rate}} <br />"
   },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "metricset.name:node_stats AND host.hostname:$ls_host AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data flow rates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.events.in_rate",
       "id": "1",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.events.out_rate",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: logstash_metrics metricset.name: node_stats AND host.hostname: $ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipelines ingest rate",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.pipeline.events.out_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: logstash_metrics AND metricset.name: pipelines AND host.hostname:$ls_host AND logstash.node.stats.pipeline.events.out_rate:>0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.process.cpu.percent",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: logstash_metrics AND metricset.name: node_stats AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Exceptions rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "type": "sum", "field": "logstash.exception.count" }
     ],
     "query": "event.dataset: logstash_logs AND logstash.log.type: Exception AND elasticsearch.cluster.id: $cluster_uid AND host.hostname: $ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JVM heap usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.jvm.mem.heap_used_percent",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: logstash_metrics AND metricset.name: node_stats AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Server level Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.cpu.cores",
         "hide": false,
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "agent.hostname: $ls_host AND event.dataset: system.cpu",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 2, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.memory.total",
         "hide": false,
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "agent.hostname: $ls_host AND event.dataset: system.memory",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "SWAP used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.memory.swap.total",
         "hide": false,
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "agent.hostname: $ls_host AND event.dataset: system.memory",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Mount points size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "system.filesystem.mount_point",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "field": "system.filesystem.total", "id": "1", "type": "max" }
       ],
       "query": "agent.hostname: $ls_host AND -system.filesystem.mount_point:\\/run* AND -system.filesystem.mount_point:\\/sys* AND -system.filesystem.mount_point:\\/dev* AND -system.filesystem.mount_point:\\/proc* AND -system.filesystem.mount_point:\\/var* AND -system.filesystem.mount_point:\\/boot",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Mount points free in bytes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "system.filesystem.mount_point",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "field": "system.filesystem.available", "id": "1", "type": "max" }
       ],
       "query": "agent.hostname: $ls_host AND -system.filesystem.mount_point:\\/run* AND -system.filesystem.mount_point:\\/sys* AND -system.filesystem.mount_point:\\/dev* AND -system.filesystem.mount_point:\\/proc* AND -system.filesystem.mount_point:\\/var* AND -system.filesystem.mount_point:\\/boot",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Mount points used",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "system.filesystem.mount_point",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "field": "system.filesystem.used.pct", "id": "1", "type": "max" }
       ],
       "query": "agent.hostname: $ls_host AND -system.filesystem.mount_point:\\/run* AND -system.filesystem.mount_point:\\/sys* AND -system.filesystem.mount_point:\\/dev* AND -system.filesystem.mount_point:\\/proc* AND -system.filesystem.mount_point:\\/var* AND -system.filesystem.mount_point:\\/boot",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.cpu.user.pct",
         "hide": false,
         "id": "1",
         "type": "avg"
        },
        {
         "field": "system.cpu.system.pct",
         "hide": false,
         "id": "3",
         "type": "avg"
        },
        {
         "field": "system.cpu.nice.pct",
         "hide": false,
         "id": "4",
         "type": "avg"
        },
        {
         "field": "system.cpu.softirq.pct",
         "hide": false,
         "id": "5",
         "type": "avg"
        },
        {
         "field": "system.cpu.irq.pct",
         "hide": false,
         "id": "6",
         "type": "avg"
        },
        {
         "field": "system.cpu.iowait.pct",
         "hide": false,
         "id": "7",
         "type": "avg"
        }
       ],
       "query": "event.dataset: system.cpu AND agent.hostname: $ls_host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.memory.actual.used.bytes",
         "hide": false,
         "id": "1",
         "type": "avg"
        },
        {
         "field": "system.memory.used.bytes",
         "hide": true,
         "id": "4",
         "type": "avg"
        },
        {
         "id": "5",
         "pipelineVariables": [
          { "name": "actual", "pipelineAgg": "1" },
          { "name": "used", "pipelineAgg": "4" }
         ],
         "settings": {
          "script": "params.actual != null && params.used != null ? params.used - params.actual : null"
         },
         "type": "bucket_script"
        },
        { "field": "system.memory.free", "id": "6", "type": "avg" }
       ],
       "query": "agent.hostname: $ls_host AND event.dataset: system.memory",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Network traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "system.network.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.network.in.bytes",
         "hide": true,
         "id": "1",
         "type": "max",
         "settings": { "script": "_value/60" }
        },
        {
         "field": "1",
         "hide": false,
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "1m" },
         "type": "derivative"
        },
        {
         "field": "system.network.out.bytes",
         "hide": true,
         "id": "5",
         "type": "max",
         "settings": { "script": "_value/60" }
        },
        {
         "field": "5",
         "hide": true,
         "id": "6",
         "pipelineAgg": "5",
         "settings": { "unit": "1m" },
         "type": "derivative"
        },
        {
         "id": "7",
         "pipelineVariables": [
          { "name": "out", "pipelineAgg": "6" }
         ],
         "settings": { "script": "params.out * -1" },
         "type": "bucket_script"
        }
       ],
       "query": "event.dataset: system.network AND agent.hostname: $ls_host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Disk Write IOPS",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "system.diskio.name",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": {
          "interval": "1m",
          "min_doc_count": "0",
          "offset": "1m",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.diskio.write.count",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "field": "1",
         "hide": true,
         "id": "4",
         "pipelineAgg": "1",
         "type": "derivative"
        },
        {
         "id": "5",
         "pipelineVariables": [
          { "name": "io", "pipelineAgg": "4" }
         ],
         "settings": { "script": "params.io / 60" },
         "type": "bucket_script"
        }
       ],
       "query": "agent.hostname: $ls_host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Processes By Memory",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "process.name",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": { "interval": "1m", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "field": "system.process.memory.rss.pct", "id": "1", "type": "max" }
       ],
       "query": "process.name:* AND agent.hostname: $ls_host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Network dropped packets",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "system.network.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.network.in.dropped",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "1m" },
         "type": "derivative"
        },
        {
         "field": "system.network.out.dropped",
         "hide": true,
         "id": "5",
         "type": "max"
        },
        {
         "field": "5",
         "hide": true,
         "id": "6",
         "pipelineAgg": "5",
         "settings": { "unit": "1m" },
         "type": "derivative"
        },
        {
         "id": "7",
         "pipelineVariables": [
          { "name": "out", "pipelineAgg": "6" }
         ],
         "settings": { "script": "params.out * -1" },
         "type": "bucket_script"
        }
       ],
       "query": "event.dataset: system.network AND agent.hostname: $ls_host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Disk Read  IOPS",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "system.diskio.name",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": {
          "interval": "1m",
          "min_doc_count": "0",
          "offset": "1m",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.diskio.read.count",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "field": "1",
         "hide": true,
         "id": "4",
         "pipelineAgg": "1",
         "type": "derivative"
        },
        {
         "id": "5",
         "pipelineVariables": [
          { "name": "io", "pipelineAgg": "4" }
         ],
         "settings": { "script": "params.io / 60" },
         "type": "bucket_script"
        }
       ],
       "query": "agent.hostname: $ls_host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Processes By CPU",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "process.name",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": { "interval": "1m", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "field": "system.process.cpu.total.pct", "id": "1", "type": "max" }
       ],
       "query": "process.name:* AND agent.hostname: $ls_host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Network error packets",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "system.network.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "system.network.in.errors",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "1m" },
         "type": "derivative"
        },
        {
         "field": "system.network.out.errors",
         "hide": true,
         "id": "5",
         "type": "max"
        },
        {
         "field": "5",
         "hide": true,
         "id": "6",
         "pipelineAgg": "5",
         "settings": { "unit": "1m" },
         "type": "derivative"
        },
        {
         "id": "7",
         "pipelineVariables": [
          { "name": "out", "pipelineAgg": "6" }
         ],
         "settings": { "script": "params.out * -1" },
         "type": "bucket_script"
        }
       ],
       "query": "event.dataset: system.network AND agent.hostname: $ls_host",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Logstash Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logstash logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "id": "1", "settings": { "limit": "100" }, "type": "logs" }
       ],
       "query": "logstash.elasticsearch.cluster.id: $cluster_uid AND ( host.hostname: $ls_host OR host.name: $ls_host)",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Flow Stats (Not for the Windows)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG Pipelines Current worker utilization",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "logstash.node.stats.pipeline.id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "logstash.node.stats.pipeline.flow.worker_utilization.current",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "elasticsearch.cluster.id: ${cluster_uid:raw} AND event.dataset: logstash_metrics AND metricset.name: pipelines AND host.hostname: $ls_host AND logstash.node.stats.pipeline.events.out_rate:>0",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "AVG Pipelines Last 1 min worker utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "logstash.node.stats.pipeline.id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "logstash.node.stats.pipeline.flow.worker_utilization.last_1_minute",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "elasticsearch.cluster.id: ${cluster_uid:raw} AND event.dataset: logstash_metrics AND metricset.name: pipelines AND host.hostname: $ls_host AND logstash.node.stats.pipeline.events.out_rate:>0",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "AVG Pipelines worker utilization (number of workers)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "logstash.node.stats.pipeline.id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "logstash.node.stats.pipeline.flow.worker_concurrency.last_15_minutes",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "elasticsearch.cluster.id: ${cluster_uid:raw} AND event.dataset: logstash_metrics AND metricset.name: pipelines AND host.hostname: $ls_host AND logstash.node.stats.pipeline.events.out_rate:>0",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "AVG Pipelines Last 1 min worker utilization more then 90%",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "logstash.node.stats.pipeline.id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "logstash.node.stats.pipeline.flow.worker_utilization.last_1_minute",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "elasticsearch.cluster.id: ${cluster_uid:raw} AND event.dataset: logstash_metrics AND metricset.name: pipelines AND host.hostname: $ls_host AND logstash.node.stats.pipeline.flow.worker_utilization.last_1_minute:>90",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Pipelines outcome rates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.pipeline.events.out_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid:raw} AND event.dataset: logstash_metrics AND metricset.name: pipelines AND host.hostname: $ls_host AND logstash.node.stats.pipeline.events.out_rate:>0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logstash logs rate per pipeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event.dataset: logstash_logs  AND elasticsearch.cluster.id: $cluster_uid AND host.hostname: $ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipelines overview",
   "type": "table",
   "gridPos": { "h": 18, "w": 13, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.pipeline.events.in",
       "id": "1",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.in_rate",
       "id": "4",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.out",
       "id": "5",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.out_rate",
       "id": "6",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.filters_failures",
       "id": "7",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.filters_failures_rate",
       "id": "8",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: ${cluster_uid} AND event.dataset: logstash_metrics AND metricset.name: pipelines AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "logstash.log.pipeline_listener_port",
       "id": "1",
       "settings": { "missing": "0" },
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND host.hostname:$ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Exceptions rate per pipeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "type": "sum", "field": "logstash.exception.count" }
     ],
     "query": "event.dataset: logstash_logs AND logstash.log.type: Exception AND elasticsearch.cluster.id: $cluster_uid AND host.hostname: $ls_host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Exception list",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.log.pipeline_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "logstash.exception.type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "type": "sum", "field": "logstash.exception.count" }
     ],
     "query": "event.dataset: logstash_logs AND logstash.log.type: Exception AND ( host.hostname: $ls_host OR host.name: $ls_host ) AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}