{
 "title": "Elasticsearch ingest pipelines overview",
 "tags": [
  "DBeastMonitor",
  "OverviewDashboard"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster Name",
    "query": {}
   },
   { "name": "es_direct_prod", "label": "Elastic datasource", "query": "marcusolsson-json-datasource" },
   { "name": "es_ingest_pipelines", "label": "es_ingest_pipelines", "query": "elasticsearch" },
   { "name": "es_ingest_pipelines_status", "label": "es_ingest_pipelines_status", "query": "elasticsearch" },
   { "name": "filebeat_logs", "label": "Elastic datasource", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Pipelines list",
   "type": "table",
   "gridPos": { "h": 22, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.count",
       "id": "1",
       "type": "max"
      },
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.in_rate",
       "hide": false,
       "id": "4",
       "type": "max"
      },
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.processors_failures",
       "hide": false,
       "id": "8",
       "type": "max"
      }
     ],
     "query": "event.dataset: pipeline_stats AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System status",
   "type": "table",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.cluster.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "id": "1",
       "type": "max",
       "field": "elasticsearch.number_of_ingest_nodes"
      },
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.id",
       "hide": false,
       "id": "3",
       "type": "cardinality"
      },
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.in_rate",
       "hide": false,
       "id": "4",
       "type": "sum"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND event.dataset: pipeline_stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ingest nodes status",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 4 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.os.cpu.percent", "language": "jsonpath", "name": "cpu", "type": "number" },
      {
       "jsonPath": "$.nodes.*.jvm.mem.heap_used_percent",
       "language": "jsonpath",
       "name": "Heap used",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/_nodes/ingest:true/stats/os,jvm,fs,indices?filter_path=cluster_name,nodes.*.name,nodes.*.os.cpu.percent,nodes.*.os.mem.total_in_bytes,nodes.*.os.mem.used_in_bytes,nodes.*.os.mem.used_percent,nodes.*.jvm.mem.heap_used_in_bytes,nodes.*.jvm.mem.non_heap_used_in_bytes,nodes.*.jvm.mem.heap_used_percent,nodes.*.jvm.mem.heap_max_in_bytes,nodes.*.fs.total.total_in_bytes,nodes.*.fs.total.available_in_bytes,nodes.*.indices.docs.count,nodes.*.indices.docs.deleted,,nodes.*.indices.shard_stats.total_count"
    }
   ]
  },
  {
   "title": "Income rates",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.id",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.in_rate",
       "id": "3",
       "type": "sum"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.stats.ingest_pipeline.in_rate: [1 TO 10000000]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Outcome rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.id",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.node.stats.ingest_pipeline.in_rate",
       "id": "3",
       "type": "sum"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.stats.ingest_pipeline.in_rate: [1 TO 10000000]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Enrich queue status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.node.id",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.node.stats.ingest.enrich.coordinator_stats.queue_size",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND event.dataset: enrich_queue_stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current number of outstanding remote requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.node.stats.ingest.enrich.coordinator_stats.remote_requests_current",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND event.dataset: enrich_queue_stats",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Elasticsearch logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Elasticsearch logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
     ],
     "query": "NOT fileset.name: audit AND NOT fileset.name: gc AND NOT log.logger: plugins.security.audit.ecs AND NOT elasticsearch.component: o.e.m.j.JvmGcMonitorService AND NOT log.logger: org.elasticsearch.monitor.jvm.JvmGcMonitorService AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}