{
 "title": "Elasticsearch shards overview dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster Name",
    "query": {}
   },
   { "name": "es_shards_stats", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "es_shards_stats_status", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "es_index_stats", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "es_index_stats_status", "label": "Elastic datasource", "query": "elasticsearch" }
  ]
 },
 "panels": [
  { "title": "Indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Indexing rate per index ( For indices with indexing rate greater than 1 Events/s )",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.index.total.indexing.index_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.index.total.indexing.index_rate: [1 TO 1000000]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexing rates per node ( For indices with rate greater than 1 Events/s)",
   "type": "table",
   "gridPos": { "h": 23, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "20" },
       "type": "terms"
      },
      {
       "field": "elasticsearch.node.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.shard.indexing.index_rate",
       "id": "4",
       "type": "sum"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.indexing.index_rate: [1 TO 100000]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average index latency per Node per Shard ( latency greater than 1 ms) ",
   "type": "table",
   "gridPos": { "h": 23, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "20" },
       "type": "terms"
      },
      {
       "field": "elasticsearch.node.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.shard.indexing.index_latency",
       "id": "4",
       "type": "avg"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.indexing.index_latency: [1 TO 100000]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top index patterns ingest rate",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.shard.indexing.index_rate",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top index ingest rate",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.shard.indexing.index_rate",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexing latency per index ( For indices with latency greater than 1 ms) ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.index.total.indexing.index_latency",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.index.total.indexing.index_latency: [1 TO 1000000]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Number of shards queried in the last period per node per Index pattern",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.index_pattern",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "15" },
       "type": "terms"
      },
      {
       "field": "elasticsearch.node.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.shard.search.query_last_period",
       "id": "4",
       "type": "sum"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.search.query_last_period: [1 TO 100000]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Fetch operations per index per node per shard in the last period",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "15" },
       "type": "terms"
      },
      {
       "field": "elasticsearch.node.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "id": "4",
       "type": "avg",
       "field": "elasticsearch.shard.search.fetch_last_period"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.search.fetch_last_period: [1 TO 100000]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Query latency per node per index per shard ( greater than 100ms)",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 42 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "15" },
       "type": "terms"
      },
      {
       "field": "elasticsearch.node.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "id": "4",
       "type": "avg",
       "field": "elasticsearch.shard.search.query_latency"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.search.query_latency: [100 TO 100000]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Fetch latency per index per node per shard ( greater than 1ms)",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 42 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.index.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "15" },
       "type": "terms"
      },
      {
       "field": "elasticsearch.node.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "id": "4",
       "type": "avg",
       "field": "elasticsearch.shard.search.fetch_latency"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.shard.search.fetch_latency: [1 TO 100000]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}