{
 "title": "Elasticsearch tasks analytics",
 "tags": [
  "DBeastMonitor",
  "OverviewDashboard"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster Name",
    "query": {}
   },
   { "name": "es_tasks", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "es_thread_pools", "label": "Elastic Thread pools", "query": "elasticsearch" },
   { "name": "text_search_filter", "label": "Free search", "query": "*" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Search tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top tasks running time by index pattern",
   "type": "table",
   "gridPos": { "h": 18, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.task.request.index_pattern",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "elasticsearch.task.running_time",
       "id": "1",
       "type": "max"
      },
      { "field": "elasticsearch.task.task_id", "id": "3", "type": "cardinality" }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: search_task",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search tasks count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: search_task",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search tasks per node",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.task.node",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "field": "elasticsearch.task.task_id", "id": "3", "type": "cardinality" }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: search_task",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search response time (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Response time (s)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch.task.running_time",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: search_task",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search Thread pool rejects (rejects/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.node.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch.node.stats.thread_pool.rejected_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.stats.thread_pool.name: search",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top running queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "settings": { "size": "50" }, "type": "raw_data" }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: search_task AND elasticsearch.task.request.query:* AND ${text_search_filter:raw} ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ESQL tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top ESQL tasks running time by index pattern",
     "type": "table",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 29 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.task.request.index_pattern",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.task.running_time",
         "id": "1",
         "type": "max"
        },
        { "field": "elasticsearch.task.task_id", "id": "3", "type": "cardinality" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: esql_task",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "ESQL tasks count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 7, "y": 29 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.task.node",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: esql_task",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Tasks per node",
     "type": "table",
     "gridPos": { "h": 16, "w": 6, "x": 18, "y": 29 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.task.node",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
         "type": "terms"
        }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "field": "elasticsearch.task.task_id", "id": "3", "type": "cardinality" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: esql_task",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Max Response time (s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 7, "y": 37 },
     "targets": [
      {
       "alias": "Response time (s)",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "elasticsearch.task.running_time",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: esql_task",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top running queries",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "id": "1", "settings": { "size": "50" }, "type": "raw_data" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: esql_task AND elasticsearch.task.request.query:* AND ${text_search_filter:raw} ",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Write tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 17, "w": 5, "x": 0, "y": 55 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.task.node",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: write_task",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Write operations count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 5, "y": 55 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.task.node",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: write_task",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Ingest Bulk analytics",
     "type": "table",
     "gridPos": { "h": 17, "w": 13, "x": 11, "y": 55 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.task.request.index_pattern",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "elasticsearch.task.request.bulk_size",
         "id": "1",
         "type": "avg"
        },
        {
         "field": "elasticsearch.task.request.bulk_size",
         "id": "3",
         "type": "max"
        },
        {
         "field": "elasticsearch.task.request.bulk_size",
         "id": "4",
         "type": "min"
        },
        {
         "field": "elasticsearch.task.running_time",
         "id": "5",
         "type": "avg"
        },
        {
         "field": "elasticsearch.task.running_time",
         "id": "6",
         "type": "max"
        },
        { "id": "8", "type": "count" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: write_task",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Write Thread pool rejects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 64 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.node.name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "elasticsearch.node.stats.thread_pool.rejected_rate",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.stats.thread_pool.name: write",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top running queries",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "id": "1", "settings": { "size": "100" }, "type": "raw_data" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: write_task AND ${text_search_filter:raw}",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Another tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tasks actions list ",
     "type": "table",
     "gridPos": { "h": 25, "w": 5, "x": 0, "y": 82 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.task.action",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Another tasks count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 9, "y": 82 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: general AND ${text_search_filter:raw}",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top running queries",
     "type": "table",
     "gridPos": { "h": 19, "w": 19, "x": 5, "y": 88 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "id": "1", "settings": { "size": "100" }, "type": "raw_data" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: general AND ${text_search_filter:raw}",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}