{
 "title": "Elastic stack monitoring dashboard",
 "tags": [
  "DBeastMonitor",
  "OverviewDashboard"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster Name",
    "query": {}
   },
   { "name": "es_metrics", "label": "es_metrics", "query": "elasticsearch" },
   { "name": "es_direct_prod", "label": "Elastic datasource", "query": "marcusolsson-json-datasource" },
   { "name": "kibana_direct", "label": "Kibana datasource", "query": "marcusolsson-json-datasource" },
   { "name": "es_index_stats", "label": "Elastic datasource", "query": "elasticsearch" },
   { "name": "logstash_mon_metrics_status", "label": "logstash_mon_metrics_status", "query": "elasticsearch" },
   { "name": "filebeat_logs", "label": "Elastic datasource", "query": "elasticsearch" },
   {
    "name": "mount_point",
    "label": "Mount point",
    "query": "{\"find\": \"terms\", \"field\": \"system.filesystem.mount_point\", \"query\": \"elasticsearch.cluster.id: $cluster_uid\"}"
   },
   { "name": "es_thread_pools", "label": "Elastic Thread pools", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Cluster health",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.cluster_name" },
      { "jsonPath": "$.status", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.number_of_nodes", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.number_of_data_nodes", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.unassigned_shards", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.active_shards", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.relocating_shards", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.initializing_shards", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "urlPath": "/_cluster/health"
    },
    {
     "fields": [
      { "jsonPath": "$.cluster_name" },
      { "jsonPath": "$.indices.count", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.indices.shards.total", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.indices.docs.count", "language": "jsonpath", "name": "docs_count" },
      {
       "jsonPath": "$.nodes.jvm.mem.heap_max_in_bytes",
       "language": "jsonpath",
       "name": "Total heap"
      },
      { "jsonPath": "$.indices.store.size_in_bytes", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.nodes.fs.free_in_bytes", "language": "jsonpath", "name": "" },
      { "name": "", "jsonPath": "$.indices.docs.deleted", "language": "jsonpath" }
     ],
     "method": "GET",
     "urlPath": "/_cluster/stats?filter_path=cluster_name,nodes.versions,nodes.jvm.mem.heap_max_in_bytes,fs.total_in_bytes,indices.docs.deleted,indices.docs.count,indices.store.size_in_bytes,indices.shards.total,indices.count,nodes.fs.free_in_bytes"
    }
   ]
  },
  { "title": "Cluster level rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Cluster ingest rate - EPS(Events per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch.index.summary.total.indexing.index_rate",
       "id": "1",
       "settings": { "script": "_value <= 0 ? 0 : _value" },
       "type": "max"
      },
      {
       "field": "elasticsearch.index.summary.primaries.indexing.index_rate",
       "id": "3",
       "settings": { "script": "_value <= 0 ? 0 : _value" },
       "type": "max"
      }
     ],
     "query": "event.dataset: indices_stats AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cluster Search rate - QPS(Query per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch.index.summary.total.search.query_rate",
       "id": "1",
       "settings": { "script": "_value <= 0 ? 0 : _value" },
       "type": "max"
      }
     ],
     "query": "event.dataset: indices_stats AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Nodes stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Data Hot nodes status",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 13 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      {
       "jsonPath": "$.nodes.*.indices.shard_stats.total_count",
       "language": "jsonpath",
       "name": "Shards"
      },
      { "jsonPath": "$.nodes.*.os.cpu.percent", "language": "jsonpath", "name": "CPU", "type": "number" },
      {
       "jsonPath": "$.nodes.*.jvm.mem.heap_used_percent",
       "language": "jsonpath",
       "name": "Heap used",
       "type": "number"
      },
      {
       "jsonPath": "$.nodes.*.fs.total.total_in_bytes",
       "language": "jsonpath",
       "name": "Total Storage",
       "type": "number"
      },
      {
       "jsonPath": "$.nodes.*.fs.total.available_in_bytes",
       "language": "jsonpath",
       "name": "Available storage",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/_nodes/data_hot:true/stats/os,jvm,fs,indices?filter_path=nodes.*.indices.shard_stats.total_count,nodes.*.name,nodes.*.os.cpu.percent,nodes.*.jvm.mem.heap_used_percent,nodes.*.fs.total.total_in_bytes,nodes.*.fs.total.available_in_bytes,nodes.*.version"
    },
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.version", "language": "jsonpath", "name": "Version" }
     ],
     "method": "GET",
     "urlPath": "/_nodes/data_hot:true?filter_path=nodes.*.version,nodes.*.name"
    }
   ]
  },
  {
   "title": "Dedicated coordinator nodes status",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.os.cpu.percent", "language": "jsonpath", "name": "CPU", "type": "number" },
      {
       "jsonPath": "$.nodes.*.jvm.mem.heap_used_percent",
       "language": "jsonpath",
       "name": "Heap used",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/_nodes/remote_cluster_client:true,master:false/stats/os,jvm,fs?filter_path=nodes.*.name,nodes.*.os.cpu.percent,nodes.*.jvm.mem.heap_used_percent,nodes.*.fs.total.total_in_bytes,nodes.*.fs.total.available_in_bytes"
    },
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.version", "language": "jsonpath", "name": "Version" }
     ],
     "method": "GET",
     "urlPath": "/_nodes/remote_cluster_client:true,master:false?filter_path=nodes.*.version,nodes.*.name"
    }
   ]
  },
  {
   "title": "Ingest nodes status",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.os.cpu.percent", "language": "jsonpath", "name": "CPU", "type": "number" },
      {
       "jsonPath": "$.nodes.*.jvm.mem.heap_used_percent",
       "language": "jsonpath",
       "name": "Heap used",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/_nodes/ingest:true/stats/os,jvm,fs?filter_path=nodes.*.name,nodes.*.os.cpu.percent,nodes.*.jvm.mem.heap_used_percent,nodes.*.fs.total.total_in_bytes,nodes.*.fs.total.available_in_bytes"
    },
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.version", "language": "jsonpath", "name": "Version" }
     ],
     "method": "GET",
     "urlPath": "/_nodes/ingest:true?filter_path=nodes.*.version,nodes.*.name"
    }
   ]
  },
  {
   "title": "Data Warm nodes status",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 25 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      {
       "jsonPath": "$.nodes.*.indices.shard_stats.total_count",
       "language": "jsonpath",
       "name": "Shards"
      },
      { "jsonPath": "$.nodes.*.os.cpu.percent", "language": "jsonpath", "name": "CPU", "type": "number" },
      {
       "jsonPath": "$.nodes.*.jvm.mem.heap_used_percent",
       "language": "jsonpath",
       "name": "Heap used",
       "type": "number"
      },
      {
       "jsonPath": "$.nodes.*.fs.total.total_in_bytes",
       "language": "jsonpath",
       "name": "Total Storage",
       "type": "number"
      },
      {
       "jsonPath": "$.nodes.*.fs.total.available_in_bytes",
       "language": "jsonpath",
       "name": "Available storage",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/_nodes/data_warm:true/stats/os,jvm,fs,indices?filter_path=nodes.*.indices.shard_stats.total_count,nodes.*.name,nodes.*.os.cpu.percent,nodes.*.jvm.mem.heap_used_percent,nodes.*.fs.total.total_in_bytes,nodes.*.fs.total.available_in_bytes,nodes.*.version"
    },
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.version", "language": "jsonpath", "name": "Version" }
     ],
     "method": "GET",
     "urlPath": "/_nodes/data_warm:true?filter_path=nodes.*.version,nodes.*.name"
    }
   ]
  },
  {
   "title": "Master nodes status",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 25 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.os.cpu.percent", "language": "jsonpath", "name": "CPU", "type": "number" },
      {
       "jsonPath": "$.nodes.*.jvm.mem.heap_used_percent",
       "language": "jsonpath",
       "name": "Heap used",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/_nodes/master:true/stats/os,jvm,fs?filter_path=nodes.*.name,nodes.*.os.cpu.percent,nodes.*.jvm.mem.heap_used_percent,nodes.*.fs.total.total_in_bytes,nodes.*.fs.total.available_in_bytes"
    },
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.version", "language": "jsonpath", "name": "Version" }
     ],
     "method": "GET",
     "urlPath": "/_nodes/master:true?filter_path=nodes.*.version,nodes.*.name"
    }
   ]
  },
  {
   "title": "Data Cold nodes status",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 31 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      {
       "jsonPath": "$.nodes.*.indices.shard_stats.total_count",
       "language": "jsonpath",
       "name": "Shards"
      },
      { "jsonPath": "$.nodes.*.os.cpu.percent", "language": "jsonpath", "name": "CPU", "type": "number" },
      {
       "jsonPath": "$.nodes.*.jvm.mem.heap_used_percent",
       "language": "jsonpath",
       "name": "Heap used",
       "type": "number"
      },
      {
       "jsonPath": "$.nodes.*.fs.total.total_in_bytes",
       "language": "jsonpath",
       "name": "Total Storage",
       "type": "number"
      },
      {
       "jsonPath": "$.nodes.*.fs.total.available_in_bytes",
       "language": "jsonpath",
       "name": "Available storage",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/_nodes/data_cold:true/stats/os,jvm,fs,indices?filter_path=nodes.*.indices.shard_stats.total_count,nodes.*.name,nodes.*.os.cpu.percent,nodes.*.jvm.mem.heap_used_percent,nodes.*.fs.total.total_in_bytes,nodes.*.fs.total.available_in_bytes,nodes.*.version"
    },
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.version", "language": "jsonpath", "name": "Version" }
     ],
     "method": "GET",
     "urlPath": "/_nodes/data_cold:true?filter_path=nodes.*.version,nodes.*.name"
    }
   ]
  },
  {
   "title": "Machine Learning nodes status",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 31 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.os.cpu.percent", "language": "jsonpath", "name": "CPU", "type": "number" },
      {
       "jsonPath": "$.nodes.*.jvm.mem.heap_used_percent",
       "language": "jsonpath",
       "name": "Heap used",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/_nodes/ml:true/stats/os,jvm,fs?filter_path=nodes.*.name,nodes.*.os.cpu.percent,nodes.*.jvm.mem.heap_used_percent,nodes.*.fs.total.total_in_bytes,nodes.*.fs.total.available_in_bytes"
    },
    {
     "fields": [
      { "jsonPath": "$.nodes.*.name", "name": "Node name" },
      { "jsonPath": "$.nodes.*.version", "language": "jsonpath", "name": "Version" }
     ],
     "method": "GET",
     "urlPath": "/_nodes/ml:true?filter_path=nodes.*.version,nodes.*.name"
    }
   ]
  },
  {
   "title": "Logstash - Kibana stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logstash instances status",
     "type": "table",
     "gridPos": { "h": 13, "w": 14, "x": 0, "y": 17 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "logstash.node.stats.logstash.status",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "logstash.node.stats.logstash.name",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "logstash.node.stats.logstash.host",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "logstash.node.stats.logstash.version",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "logstash.node.stats.process.cpu.percent",
         "id": "1",
         "type": "max"
        },
        {
         "field": "logstash.node.stats.jvm.mem.heap_used_percent",
         "id": "3",
         "type": "max"
        },
        {
         "field": "logstash.node.stats.events.in_rate",
         "id": "4",
         "type": "max"
        },
        {
         "field": "logstash.node.stats.events.out_rate",
         "id": "5",
         "type": "max"
        },
        { "field": "@timestamp", "id": "6", "type": "max" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: node_stats",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Kibana instances status",
     "type": "table",
     "gridPos": { "h": 13, "w": 10, "x": 14, "y": 41 },
     "targets": [
      {
       "body": "{\"timeRange\":{\"min\":\"${__from:date}\",\"max\":\"${__to:date}\"},\"codePaths\":[\"all\"]}",
       "fields": [
        { "jsonPath": "$.kibanas[*].kibana.name", "name": "Node name" },
        { "jsonPath": "$.kibanas[*].kibana.host", "language": "jsonpath", "name": "" },
        { "jsonPath": "$.kibanas[*].kibana.status", "language": "jsonpath", "name": "" },
        {
         "jsonPath": "$.kibanas[*].process.memory.resident_set_size_in_bytes",
         "language": "jsonpath",
         "name": "Heap used"
        },
        { "jsonPath": "$.kibanas[*].os.load.1m", "language": "jsonpath", "name": "Load" }
       ],
       "method": "POST",
       "urlPath": "/api/monitoring/v1/clusters/${cluster_uid}/kibana/instances"
      }
     ]
    }
   ]
  },
  {
   "title": "Mount points overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mount  point \"$mount_point\" usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "repeat": "mount_point",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "host.hostname",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "field": "system.filesystem.used.pct", "id": "1", "type": "max" }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND system.filesystem.mount_point:* AND system.filesystem.mount_point: $mount_point",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread pools overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread pools rejects per Thread poll",
     "type": "table",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.node.stats.thread_pool.name",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "elasticsearch.node.stats.thread_pool.rejected",
         "id": "1",
         "type": "max"
        },
        {
         "field": "elasticsearch.node.stats.thread_pool.rejected_rate",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Rejects",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 6, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.node.name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.thread_pool.rejected_rate",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.stats.thread_pool.name: search AND elasticsearch.node.stats.thread_pool.rejected_rate:>1",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Thread pools rejects per node",
     "type": "table",
     "gridPos": { "h": 19, "w": 6, "x": 18, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.node.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "elasticsearch.node.stats.thread_pool.rejected",
         "id": "1",
         "type": "max"
        },
        {
         "field": "elasticsearch.node.stats.thread_pool.rejected_rate",
         "id": "3",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Completed Write requests rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.node.name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.thread_pool.completed_rate",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.stats.thread_pool.name: write",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Completed Search requests rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.node.name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.thread_pool.completed_rate",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.stats.thread_pool.name: search",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Rejected Write requests rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.node.name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.thread_pool.rejected_rate",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.stats.thread_pool.name: write",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Rejected Write requests rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "elasticsearch.node.name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        {
         "field": "elasticsearch.node.stats.thread_pool.rejected_rate",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "elasticsearch.cluster.id: $cluster_uid AND elasticsearch.node.stats.thread_pool.name: write",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Shards allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data relocation",
     "type": "table",
     "gridPos": { "h": 12, "w": 13, "x": 0, "y": 10 },
     "targets": [
      {
       "fields": [
        { "jsonPath": "$[*].index" },
        { "jsonPath": "$[*].shard", "language": "jsonpath", "name": "" },
        { "jsonPath": "$[*].source_node", "language": "jsonpath", "name": "" },
        { "jsonPath": "$[*].target_node", "language": "jsonpath", "name": "" },
        { "jsonPath": "$[*].bytes_total", "language": "jsonpath", "name": "" },
        { "jsonPath": "$[*].bytes_percent", "language": "jsonpath", "name": "" },
        { "jsonPath": "$[*].files_percent", "language": "jsonpath", "name": "" },
        { "jsonPath": "$[*].translog_ops_percent", "language": "jsonpath", "name": "" }
       ],
       "method": "GET",
       "params": [
        [
         "active_only",
         "true"
        ],
        [
         "format",
         "json"
        ]
       ],
       "urlPath": "/_cat/recovery"
      }
     ]
    },
    {
     "title": "Indices with Unassigned shard",
     "type": "table",
     "gridPos": { "h": 19, "w": 6, "x": 13, "y": 41 },
     "targets": [
      {
       "fields": [
        { "jsonPath": "$[$.health != 'green'].index", "language": "jsonata", "name": "Index" },
        { "jsonPath": "$[$.health != 'green'].health", "language": "jsonata", "name": "Health" }
       ],
       "method": "GET",
       "urlPath": "/_cat/indices?h=index,health&format=json"
      }
     ]
    },
    {
     "title": "Cluster custom settings",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 19, "w": 5, "x": 19, "y": 41 },
     "options": {
      "content": "```json \n{{{json data }}}\n```"
     },
     "targets": [
      {
       "fields": [
        { "jsonPath": "$", "language": "jsonata", "name": "data" }
       ],
       "method": "GET",
       "urlPath": "/_cluster/settings"
      }
     ]
    },
    {
     "title": "Index allocation",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 22 },
     "options": {
      "content": "Index: {{index}}  <br />\nCurrent state: {{state}}  <br />\nReason: {{reason}}  <br />\nInfo: {{info}}   <br />\nExplanation: {{explanation}}  <br />"
     },
     "targets": [
      {
       "fields": [
        { "jsonPath": "$.index", "language": "jsonata", "name": "index" },
        { "jsonPath": "$.current_state", "language": "jsonata", "name": "state" },
        { "jsonPath": "$.unassigned_info.reason", "language": "jsonata", "name": "reason" },
        { "jsonPath": "$.unassigned_info.at", "language": "jsonata", "name": "info" },
        { "jsonPath": "$.allocate_explanation", "language": "jsonata", "name": "explanation" }
       ],
       "method": "GET",
       "urlPath": "/_cluster/allocation/explain"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "fields": [
        { "jsonPath": "" }
       ],
       "method": "GET",
       "metrics": [
        { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
       ],
       "query": "NOT fileset.name: audit AND NOT fileset.name: gc AND NOT log.logger: plugins.security.audit.ecs AND NOT elasticsearch.component: o.e.m.j.JvmGcMonitorService AND NOT log.logger: org.elasticsearch.monitor.jvm.JvmGcMonitorService AND elasticsearch.cluster.id: $cluster_uid",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}