{
 "title": "Logstash overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster UID",
    "query": {}
   },
   { "name": "logstash_mon_metrics", "label": "logstash_mon_metrics", "query": "elasticsearch" },
   { "name": "logstash_mon_metrics_status", "label": "logstash_mon_metrics_status", "query": "elasticsearch" },
   { "name": "logstash_mon_logs", "label": "logstash_mon_logs", "query": "elasticsearch" },
   { "name": "logstash_mon_logs_ports", "label": "logstash_mon_logs_ports", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "System status",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "elasticsearch.cluster.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "field": "host.hostname", "id": "1", "type": "cardinality" },
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "3",
       "type": "cardinality"
      },
      {
       "field": "logstash.node.stats.pipeline.events.in_rate",
       "id": "4",
       "type": "sum"
      },
      {
       "field": "logstash.node.stats.pipeline.events.out_rate",
       "id": "5",
       "type": "sum"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid AND metricset.name: pipelines",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Outcome rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.logstash.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.events.out_rate",
       "id": "3",
       "type": "avg"
      }
     ],
     "query": "event.dataset: logstash_metrics AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logstash instances status",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.hostname",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "logstash.node.stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "logstash.node.stats.logstash.status",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "logstash.node.stats.logstash.version",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.events.in_rate",
       "id": "1",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.events.out_rate",
       "id": "5",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.process.cpu.percent",
       "id": "6",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.jvm.mem.heap_used_percent",
       "id": "7",
       "type": "max"
      }
     ],
     "query": "event.dataset: logstash_metrics AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Outcome rate per Logstash",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.hostname",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.events.out_rate",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "event.dataset: logstash_metrics AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pipelines overview",
   "type": "table",
   "gridPos": { "h": 20, "w": 14, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "host.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.pipeline.events.in",
       "id": "1",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.in_rate",
       "id": "4",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.out",
       "id": "5",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.out_rate",
       "id": "6",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.plugins.filters.failures",
       "id": "7",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.plugins.filters.failures_rate",
       "id": "8",
       "type": "max"
      }
     ],
     "query": "event.dataset: logstash_metrics AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "logstash.log.pipeline_listener_port",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Exception list",
   "type": "table",
   "gridPos": { "h": 20, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.hostname",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "logstash.node.stats.pipeline.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "logstash.exception.type",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event.dataset: logstash_logs AND logstash.log.type: exception AND elasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}