{
 "title": "Logstash pipeline analytics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_uid",
    "label": "Cluster UID",
    "query": {}
   },
   { "name": "es_direct_mon", "label": "Elastic datasource", "query": "marcusolsson-json-datasource" },
   { "name": "logstash_mon_metrics", "label": "logstash_mon_metrics", "query": "elasticsearch" },
   { "name": "logstash_mon_logs", "label": "logstash_mon_logs", "query": "elasticsearch" },
   {
    "name": "ls_host",
    "label": "Logstash host",
    "query": {}
   },
   {
    "name": "pipeline_id",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Pipeline information",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "Pipeline: {{pipeline_name}} <br />\nLogstash host: {{host}} <br />\nLogstash name: {{name}} <br />\nNumber of filters failures: {{filters_failures}} <br />"
   },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.hits.hits[0]._source.logstash.node.stats.logstash.host",
       "name": "host"
      },
      {
       "jsonPath": "$.hits.hits[0]._source.logstash.node.stats.logstash.name",
       "language": "jsonpath",
       "name": "name"
      },
      {
       "jsonPath": "$.hits.hits.[0]._source.logstash.node.stats.pipeline.id",
       "language": "jsonpath",
       "name": "pipeline_name"
      },
      {
       "jsonPath": "$.hits.hits.[0]._source.logstash.node.stats.pipeline.filters_failures",
       "language": "jsonpath",
       "name": "filters_failures"
      }
     ],
     "method": "GET",
     "params": [
      [
       "q",
       "logstash.node.stats.pipeline.id:$pipeline_id AND host.hostname:$ls_host AND elasticsearch.cluster.id: ${cluster_uid}"
      ]
     ],
     "urlPath": "/dbeast-mon-logstash-metrics-status/_search"
    }
   ]
  },
  {
   "title": "Pipeline ingest",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      {
       "field": "logstash.node.stats.pipeline.events.in_rate",
       "id": "1",
       "type": "max"
      },
      {
       "field": "logstash.node.stats.pipeline.events.out_rate",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "metricset.name: pipelines AND logstash.node.stats.pipeline.id:$pipeline_id AND host.hostname:$ls_host AND elasticsearch.cluster.id: ${cluster_uid}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline flow",
   "type": "table",
   "gridPos": { "h": 23, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.pipeline.plugins.filters[*].name",
       "name": "plugin_name"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.pipeline.plugins.filters[*].id",
       "language": "jsonpath",
       "name": "plugin_id"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.pipeline.plugins.filters[*].events.in",
       "language": "jsonpath",
       "name": "in"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.pipeline.plugins.filters[*].events.in_rate",
       "language": "jsonpath",
       "name": "in_rate"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.pipeline.plugins.filters[*].events.out",
       "language": "jsonpath",
       "name": "out"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.pipeline.plugins.filters[*].events.out_rate",
       "language": "jsonpath",
       "name": "out_rate"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.pipeline.plugins.filters[*].events.($exists(latency) ? latency: 0)",
       "language": "jsonata",
       "name": "latency"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.pipeline.plugins.filters[*].($exists(failures) ? failures: 0)",
       "language": "jsonata",
       "name": "failures"
      },
      {
       "jsonPath": "$.hits.hits[*]._source.logstash.node.stats.pipeline.plugins.filters[*].($exists(failures_rate) ? failures_rate: 0)",
       "language": "jsonata",
       "name": "failures_rate"
      }
     ],
     "method": "GET",
     "params": [
      [
       "q",
       "logstash.node.stats.pipeline.id:$pipeline_id AND host.hostname:$ls_host AND elasticsearch.cluster.id: ${cluster_uid}"
      ]
     ],
     "urlPath": "/dbeast-mon-logstash-metrics-status/_search"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event.dataset: logstash_logs AND logstash.log.type: Exception AND logstash.node.stats.pipeline.id: $pipeline_id AND host.hostname:$ls_host AND elasticsearch.cluster.id: ${cluster_uid}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Exceptions list ",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logstash.exception.type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event.dataset: logstash_logs AND logstash.log.type: Exception AND ( host.hostname: $ls_host OR host.name: $ls_host) AND logstash.log.pipeline_name: $pipeline_id AND \nelasticsearch.cluster.id: $cluster_uid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logstash exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "metrics": [
      { "id": "1", "settings": { "size": "25" }, "type": "raw_data" }
     ],
     "query": "event.dataset: logstash_logs AND logstash.log.type: Exception AND ( host.hostname: $ls_host OR host.name: $ls_host) AND logstash.log.pipeline_name: $pipeline_id AND \nelasticsearch.cluster.id: ${cluster_uid}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}