name: Release Plugin Attestation Test

on:
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build & Release Plugin
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build, sign, package and release plugin
        uses: grafana/plugin-actions/build-plugin@main
        with:
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          attestation: true
